# Generated by Django 3.2.7 on 2021-09-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recipeingredientunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredientunit',
            old_name='ingrdient',
            new_name='ingredient',
        ),
    ]
