# Generated by Django 3.2.7 on 2021-09-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_address_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='main.person'),
        ),
    ]
