# Generated by Django 3.2.7 on 2021-09-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_phone_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='phone_type',
        ),
        migrations.AddField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('emergency', 'Emergency'), ('home', 'Home'), ('work', 'Work')], default='mobile', max_length=50),
        ),
    ]
